### ISSUE TITLE
plugin not working on aws with instance profile sourced temporary credentials

### ISSUE THREAD

**Issue by eblfo** [thomasmichaelwallace/serverless-better-credentials#31]
**Describe the bug**

running `sls package` on instance with instance profile sourced temporary aws credentials the following error shows up: `ENOENT: no such file or directory, open '/home/node/.aws/credentials'`

adding the file (touch), a new error: `ProcessCredentialsProviderFailure: Profile default not found` (unsetting the variable with `AWS_PROFLE=` does not work)

**Expected behavior**

if no profile is set - use instance profile credentials

**Screenshots**

normal call:
```
$ SERVICE_NAME="staging-portal" npx serverless package --stage=dev

Packaging staging-portal for stage dev (us-east-1)
Environment: linux, node 16.20.0, framework 3.31.0 (local), plugin 6.2.3, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: ENOENT: no such file or directory, open '/home/node/.aws/credentials'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.readFileSync (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/util.js:95:26)
    at IniLoader.parseFile (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:6:47)
    at IniLoader.loadFrom (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Object.getProfilesFromSharedConfig (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/util.js:962:39)
    at ProcessCredentials.load (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials/process_credentials.js:75:31)
    at ProcessCredentials.coalesceRefresh (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials.js:205:12)
    at ProcessCredentials.refresh (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials/process_credentials.js:163:10)
    at ProcessCredentials.get (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials.js:122:12)
    at resolveNext (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:125:17)
    at /opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:126:13
    at /opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials.js:124:23
    at /opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials.js:212:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

2 deprecations found: run 'serverless doctor' for more details
```

with empty credentials file
```
$ SERVICE_NAME="staging-portal" npx serverless package --stage=dev

Packaging staging-portal for stage dev (us-east-1)
Environment: linux, node 16.20.0, framework 3.31.0 (local), plugin 6.2.3, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: ENOENT: no such file or directory, open '/home/node/.aws/credentials'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.readFileSync (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/util.js:95:26)
    at IniLoader.parseFile (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:6:47)
    at IniLoader.loadFrom (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Object.getProfilesFromSharedConfig (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/util.js:962:39)
    at ProcessCredentials.load (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials/process_credentials.js:75:31)
    at ProcessCredentials.coalesceRefresh (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials.js:205:12)
    at ProcessCredentials.refresh (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials/process_credentials.js:163:10)
    at ProcessCredentials.get (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials.js:122:12)
    at resolveNext (/opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:125:17)
    at /opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:126:13
    at /opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials.js:124:23
    at /opt/buildagent/work/73c5c0396a294f8/services/lambda-api/node_modules/aws-sdk/lib/credentials.js:212:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

2 deprecations found: run 'serverless doctor' for more details
```

sls yml - plugins used
```
frameworkVersion: '3.31.0'

plugins:
  - serverless-better-credentials # needs to be the first plugin, bypass sls aws credential resolving and add sso - does not work with instance profile credentials
  - serverless-domain-manager # careful to update, latest version uses aws sdk v3
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-ifelse

custom:
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}

provider:
  name: aws
  region: ${self:custom.region}
  deploymentMethod: direct

```

**Desktop (please complete the following information):**
see debug output above

**Comment by guiyom-e** [comment]
@eblfo what version of `serverless-better-credentials` are you using ?
Have you tried v1.2.1 (with the latest `aws-sdk` v2 package installed, as it is a peer-dependency) ?

Could you share what your config file look like (~/.aws/config) ?

**Comment by eblfo** [comment]
ok - i have to extend the problem description:

the issue happens when using `credential_process` and `AWS_PROFILE=LF_TEST_DEV_SDK`

regardless on plugin version
installed latest aws cli prior running

see here:
```$ AWS_SDK_LOAD_CONFIG=1 AWS_PROFILE=LF_TEST_DEV_SDK npx serverless package --stage=dev```

with the following config:
```
[profile LF_TEST_DEV_SDK]  
region = us-east-1
output = json
credential_process = "/bin/bash" "/tmp/aws_credential_process.sh"

[profile LF_TEST_DEV_SSO]
region = us-east-1
output = json
sso_session = LF_TEST_DEV_SSO
sso_account_id = ...accountID...
sso_role_name = ssoAccess

[sso-session LF_TEST_DEV_SSO]
sso_start_url = https://...sso..name....awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```

the external process `/tmp/aws_credential_process.sh` makes use of the actual SSO profile to manage retrieving temp credentials. this works fine with starting our nodeJS server i.e. `AWS_PROFILE=LF_TEST_DEV_SDK AWS_SDK_LOAD_CONFIG=1 node --inspect -r ts-node/register ./src/server.ts`.

**Comment by eblfo** [comment]
i tried 1.2.1 and its the same error

there is no aws config file as the instance profile of the aws ec2 instance makes sure credentials are available (aws-sdk takes care)

currently i remove the use of the plugin when run on ec2 instance (CI process)

**Comment by thomasmichaelwallace** [comment]
It's a bit late, but I've added a bit to the readme about how to deal with this CI/CD scenario by _creating_ a temporary `~/.aws/credentials` file- see:

https://github.com/thomasmichaelwallace/serverless-better-credentials?tab=readme-ov-file#troubleshooting

I'll close this issue for now, but feel free to re-open if you have any trouble.

**Comment by eblfo** [comment]
well, my solution is to remove the plugin off the sls.yml during CI/CD

**Comment by eblfo** [comment]
tx for your effort

**Comment by thomasmichaelwallace** [comment]
Hah, _also_ a good solution 😄
